In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding,Activation,Dropout
from tensorflow.keras.layers import Conv1D,MaxPooling1D,GlobalMaxPooling1D
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
from numpy import array
import pandas as pd

In [3]:
df=pd.read_csv('data/sentiment140.csv',encoding='latin1',header=None)

In [4]:
df

0           1                             2         3  \
0        0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1        0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2        0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3        0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4        0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
...     ..         ...                           ...       ...   
1599995  4  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996  4  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997  4  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998  4  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599999  4  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                       4                                                  5  
0        _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1          scotthamilton  is upset that he can't update his Facebook by ...  
2               mattycus  @Kenichan I dived many times for the ball. Man...  
3                ElleCTF    my whole body feels itchy and like its on fire   
4                 Karoli  @nationwideclass no, it's not behaving at all....  
...                  ...                                                ...  
1599995  AmandaMarie1028  Just woke up. Having no school is the best fee...  
1599996      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...  
1599997           bpbabe  Are you ready for your MoJo Makeover? Ask me f...  
1599998     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...  
1599999   RyanTrevMorris  happy #charitytuesday @theNSPCC @SparksCharity...  

[1600000 rows x 6 columns]

In [5]:
df=df[[5,0]]
df.columns=['twits','sentiment']
df.head()

twits  sentiment
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...          0
1  is upset that he can't update his Facebook by ...          0
2  @Kenichan I dived many times for the ball. Man...          0
3    my whole body feels itchy and like its on fire           0
4  @nationwideclass no, it's not behaving at all....          0

In [6]:
df0=df[df['sentiment']==0].sample(2000)
df4=df[df['sentiment']==4].sample(2000)

In [7]:
df=df0.append(df4).reset_index()

In [8]:
df.head()

index                                              twits  sentiment
0  734259  Morning, HUGE lie in. Think I will attempt to ...          0
1   42474  I got jipped! My firecracker popsicle only has...          0
2  492239                 thanks babe :/ my head hurts alot           0
3   96704                Wants to feel better, so baaaadly!           0
4  315996                   @alex_levin haha i know right??           0

In [9]:
df=df.drop(['index'],axis=1)
df

twits  sentiment
0     Morning, HUGE lie in. Think I will attempt to ...          0
1     I got jipped! My firecracker popsicle only has...          0
2                    thanks babe :/ my head hurts alot           0
3                   Wants to feel better, so baaaadly!           0
4                      @alex_levin haha i know right??           0
...                                                 ...        ...
3995  @mytutorialfeed you can dm me the link, I'll a...          4
3996      I got the greenday tickets in the mail today           4
3997  IM DONE TWIITERING PPL WHO DONT TWIT BACK...JE...          4
3998  watching Armagedon &amp; eating goldfish&lt;3....          4
3999  People who don't answer their texts will be CU...          4

[4000 rows x 2 columns]

In [10]:
text=df['twits'].tolist()
text

['Morning, HUGE lie in. Think I will attempt to go for a run ',
 "I got jipped! My firecracker popsicle only has two colors  I'm missing out on the white flavor ;-;",
 'thanks babe :/ my head hurts alot ',
 'Wants to feel better, so baaaadly! ',
 '@alex_levin haha i know right?? ',
 "update: Lock smith not needed. Friends mom has my spare keys. She was supposed to drop it off. I'm on my break and i can't leave. ",
 "@ETown_Lesley OMG I KNOW! I just can't get over all the children. 8 of them. Will be so complicated... so sad ",
 'Why is everyone not online ',
 "I can't creat a myspace ",
 "lets hope i can sleep tonight cause if i can't you will be seeing a lot of tweet about it and i will be grumpy like i was today ",
 "@shanizzy Hush silly!! I found out today that one of the kids n Cam room has the swine flu and now he don't feel good and is warm. ",
 "@pmayroy cause i wasn't there! ",
 'Wide awake for no good reason ',
 'I am never drinking again  well... Till next time ;-)',
 "Can't 

In [11]:
y=df['sentiment']

In [33]:
y=np.array(y)

In [13]:
token=Tokenizer()
token.fit_on_texts(text)

In [14]:
token

In [15]:
token.word_index

{'i': 1,
 'to': 2,
 'the': 3,
 'a': 4,
 'my': 5,
 'and': 6,
 'you': 7,
 'it': 8,
 'is': 9,
 'for': 10,
 'in': 11,
 'of': 12,
 'me': 13,
 'on': 14,
 'so': 15,
 'have': 16,
 'that': 17,
 "i'm": 18,
 'but': 19,
 'be': 20,
 'just': 21,
 'with': 22,
 'not': 23,
 'at': 24,
 'was': 25,
 'now': 26,
 'up': 27,
 'this': 28,
 'day': 29,
 'get': 30,
 'no': 31,
 'good': 32,
 'out': 33,
 'are': 34,
 'like': 35,
 'all': 36,
 'do': 37,
 'go': 38,
 "it's": 39,
 'quot': 40,
 'today': 41,
 'too': 42,
 'http': 43,
 'we': 44,
 'from': 45,
 'love': 46,
 'time': 47,
 'got': 48,
 'going': 49,
 'u': 50,
 'work': 51,
 'amp': 52,
 'really': 53,
 'your': 54,
 'one': 55,
 'lol': 56,
 'know': 57,
 'back': 58,
 'will': 59,
 'about': 60,
 'im': 61,
 "don't": 62,
 'well': 63,
 'see': 64,
 'can': 65,
 'what': 66,
 'am': 67,
 'home': 68,
 'if': 69,
 'new': 70,
 'has': 71,
 'its': 72,
 'had': 73,
 'oh': 74,
 'com': 75,
 'thanks': 76,
 'how': 77,
 "can't": 78,
 'off': 79,
 'some': 80,
 'think': 81,
 'want': 82,
 '2': 83,


In [16]:
vocab_size=len(token.word_index)+1
vocab_size

10144

In [17]:
x=['i to the a my']

In [18]:
token.texts_to_sequences(x)

[[1, 2, 3, 4, 5]]

In [19]:
encoded_text=token.texts_to_sequences(text)

In [20]:
print(encoded_text)

[[113, 877, 1431, 11, 81, 1, 59, 1432, 2, 38, 10, 4, 342], [1, 48, 3030, 5, 3031, 3032, 130, 71, 247, 1909, 18, 417, 33, 14, 3, 878, 3033], [76, 1433, 5, 418, 343, 992], [388, 2, 111, 138, 15, 3034], [1434, 3035, 107, 1, 57, 115], [605, 1910, 1435, 23, 993, 241, 419, 71, 5, 1911, 3036, 134, 25, 784, 2, 1436, 8, 79, 18, 14, 5, 562, 6, 1, 78, 306], [1912, 1913, 188, 1, 57, 1, 21, 78, 30, 145, 36, 3, 1175, 288, 12, 148, 59, 20, 15, 3037, 15, 104], [94, 9, 193, 23, 1176], [1, 78, 3038, 4, 1177], [563, 87, 1, 65, 121, 126, 389, 69, 1, 78, 7, 59, 20, 358, 4, 307, 12, 272, 60, 8, 6, 1, 59, 20, 1178, 35, 1, 25, 41], [3039, 1914, 879, 1, 324, 33, 41, 17, 55, 12, 3, 390, 223, 1437, 420, 71, 3, 880, 657, 6, 26, 114, 62, 111, 32, 6, 9, 606], [3040, 389, 1, 469, 85], [1438, 470, 10, 31, 32, 658], [1, 67, 155, 659, 105, 63, 371, 132, 47], [78, 273, 716, 1439, 3041, 1915, 18, 118, 104], [717, 785, 344, 10, 5, 471], [24, 3, 1916, 3042], [297, 472, 97, 881, 23, 1917], [3043, 12, 786, 1, 48, 158, 70, 42

In [51]:
max_len=0
for i in range(4000):    
    if len(encoded_text[i]) > max_len:
        max_len=len(encoded_text[i])
print(max_len)

33


In [52]:
x=pad_sequences(encoded_text,maxlen=33,padding='post')
#just sequence of words, not vector

In [53]:
print(x)

[[  113   877  1431 ...     0     0     0]
 [    1    48  3030 ...     0     0     0]
 [   76  1433     5 ...     0     0     0]
 ...
 [   61   243 10137 ...     0     0     0]
 [  139 10139    52 ...     0     0     0]
 [  137   166    62 ...     0     0     0]]


In [54]:
x.shape

(4000, 33)

In [55]:
y.shape

(4000,)

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2,stratify=y)

In [57]:
x_train.shape,x_test.shape,y_train.shape

((3200, 33), (800, 33), (3200,))

In [58]:
type(x_train),type(y_train)

(numpy.ndarray, numpy.ndarray)

In [59]:
vec_size=300

model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=vec_size, input_length=33))

model.add(Conv1D(64,8,activation='relu'))
model.add(MaxPooling1D(2))
model.add(Dropout(0.2))

model.add(Dense(32,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(16,activation='relu'))

model.add(GlobalMaxPooling1D())
model.add(Dense(1,activation='sigmoid'))

In [60]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [61]:
hist=model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Train on 3200 samples, validate on 800 samples
Epoch 1/5
3200/3200 [==============================] - 5s 1ms/sample - loss: -181.3057 - accuracy: 0.0219 - val_loss: -657.6521 - val_accuracy: 0.0000e+00
Epoch 2/5
3200/3200 [==============================] - 4s 1ms/sample - loss: -18531.5555 - accuracy: 0.0000e+00 - val_loss: -43590.2363 - val_accuracy: 0.0000e+00
Epoch 3/5
3200/3200 [==============================] - 4s 1ms/sample - loss: -299553.8062 - accuracy: 0.0000e+00 - val_loss: -522021.2762 - val_accuracy: 0.0000e+00
Epoch 4/5
3200/3200 [==============================] - 4s 1ms/sample - loss: -1957124.0794 - accuracy: 0.0000e+00 - val_loss: -2887625.5300 - val_accuracy: 0.0000e+00
Epoch 5/5
3200/3200 [==============================] - 4s 1ms/sample - loss: -8468504.1713 - accuracy: 0.0000e+00 - val_loss: -10892914.9800 - val_accuracy: 0.0000e+00


In [32]:
x_test

array([[   9,  256, 2972, ...,    0,    0,    0],
       [7725,  150,   64, ...,    0,    0,    0],
       [ 104,   11,    5, ...,    0,    0,    0],
       ...,
       [   1,  194,  344, ...,    0,    0,    0],
       [  61,   15,  745, ...,    0,    0,    0],
       [ 393,   21,   48, ...,    0,    0,    0]])

In [45]:
def get_encoded(x):
    x=token.texts_to_sequences(x)
    x=pad_sequences(x,maxlen=31,padding='post')
    return x

In [46]:
x=['worst services. will not come again']

In [47]:
model.predict_classes(get_encoded(x))

array([[1]])